/*! 
* SPP English Localization
* Created By Eugene 19/11/2015 Globalize 0.x
* Modified By Eugene 14/09/2016 Globalize 1.x
*/

(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        define(function (require, exports, module) {
            factory(require("../message"))
        })
    }
    else {
        factory(DevExpress.localization.message)
    }
}(this, function (message) {
    message.load({
        en: {
            Back: "Back",
            Cancel: "Cancel",
            Clear: "Clear",
            Done: "Done",
            Loading: "Loading...",
            No: "No",
            OK: "OK",
            Search: "Search",
            Select: "Select...",
            Yes: "Yes",
            "dxCalendar-ariaWidgetName": "Calendar",
            "dxCalendar-todayButtonText": "Today",
            "dxCollectionWidget-noDataText": "NA",
            "dxColorView-ariaAlpha": "Transparency",
            "dxColorView-ariaBlue": "Blue",
            "dxColorView-ariaGreen": "Green",
            "dxColorView-ariaHex": "Color code",
            "dxColorView-ariaRed": "Red",
            "dxDataGrid-applyFilterText": "Apply filter",
            "dxDataGrid-ariaCollapse": "Collapse",
            "dxDataGrid-ariaColumn": "Column",
            "dxDataGrid-ariaDataGrid": "Data grid",
            "dxDataGrid-ariaExpand": "Expand",
            "dxDataGrid-ariaFilterCell": "Filter cell",
            "dxDataGrid-ariaSearchInGrid": "Search in data grid",
            "dxDataGrid-ariaSelectAll": "Select all",
            "dxDataGrid-ariaSelectRow": "Select row",
            "dxDataGrid-ariaValue": "Value",
            "dxDataGrid-columnChooserEmptyText": "Drag a column here to hide it",
            "dxDataGrid-columnChooserTitle": "Column Chooser",
            "dxDataGrid-columnFixingFix": "Fix",
            "dxDataGrid-columnFixingLeftPosition": "To the left",
            "dxDataGrid-columnFixingRightPosition": "To the right",
            "dxDataGrid-columnFixingUnfix": "Unfix",
            "dxDataGrid-editingAddRow": "Add a row",
            "dxDataGrid-editingCancelAllChanges": "Discard changes",
            "dxDataGrid-editingCancelRowChanges": "Cancel",
            "dxDataGrid-editingConfirmDeleteMessage": "Are you sure you want to delete this record?",
            "dxDataGrid-editingConfirmDeleteTitle": "",
            "dxDataGrid-editingDeleteRow": "Delete",
            "dxDataGrid-editingEditRow": "Edit",
            "dxDataGrid-editingSaveAllChanges": "Save changes",
            "dxDataGrid-editingSaveRowChanges": "Save",
            "dxDataGrid-editingUndeleteRow": "Undelete",
            "dxDataGrid-excelFormat": "Excel file",
            "dxDataGrid-exportTo": "Export to",
            "dxDataGrid-exportToExcel": "Export to Excel file",
            "dxDataGrid-falseText": "false",
            "dxDataGrid-filterRowOperationContains": "Contains",
            "dxDataGrid-filterRowOperationEndsWith": "Ends with",
            "dxDataGrid-filterRowOperationEquals": "Equals",
            "dxDataGrid-filterRowOperationGreater": "Greater than",
            "dxDataGrid-filterRowOperationGreaterOrEquals": "Greater than or equal to",
            "dxDataGrid-filterRowOperationLess": "Less than",
            "dxDataGrid-filterRowOperationLessOrEquals": "Less than or equal to",
            "dxDataGrid-filterRowOperationNotContains": "Does not contain",
            "dxDataGrid-filterRowOperationNotEquals": "Does not equal",
            "dxDataGrid-filterRowOperationStartsWith": "Starts with",
            "dxDataGrid-filterRowResetOperationText": "Reset",
            "dxDataGrid-filterRowShowAllText": "(All)",
            "dxDataGrid-groupContinuedMessage": "Continued from the previous page",
            "dxDataGrid-groupContinuesMessage": "Continues on the next page",
            "dxDataGrid-groupPanelEmptyText": "Drag a column header here to group by that column",
            "dxDataGrid-headerFilterCancel": "Cancel",
            "dxDataGrid-headerFilterEmptyValue": "(Blanks)",
            "dxDataGrid-headerFilterOK": "OK",
            "dxDataGrid-noDataText": "No data",
            "dxDataGrid-searchPanelPlaceholder": "Search...",
            "dxDataGrid-selectedRows": "Selected rows",
            "dxDataGrid-sortingAscendingText": "Sort Ascending",
            "dxDataGrid-sortingClearText": "Clear Sorting",
            "dxDataGrid-sortingDescendingText": "Sort Descending",
            "dxDataGrid-summaryAvg": "Avg: {0}",
            "dxDataGrid-summaryAvgOtherColumn": "Avg of {1} is {0}",
            "dxDataGrid-summaryCount": "Count: {0}",
            "dxDataGrid-summaryMax": "Max: {0}",
            "dxDataGrid-summaryMaxOtherColumn": "Max of {1} is {0}",
            "dxDataGrid-summaryMin": "Min: {0}",
            "dxDataGrid-summaryMinOtherColumn": "Min of {1} is {0}",
            "dxDataGrid-summarySum": "Sum: {0}",
            "dxDataGrid-summarySumOtherColumn": "Sum of {1} is {0}",
            "dxDataGrid-trueText": "true",
            "dxDataGrid-validationCancelChanges": "Cancel changes",
            "dxDateBox-simulatedDataPickerTitleDate": "Select date",
            "dxDateBox-simulatedDataPickerTitleDateTime": "Select date and time",
            "dxDateBox-simulatedDataPickerTitleTime": "Select time",
            "dxDateBox-validation-datetime": "Value must be a date or time",
            "dxFileSaver-fileExported": "File exported",
            "dxFileUploader-Gb": "Gb",
            "dxFileUploader-Mb": "Mb",
            "dxFileUploader-bytes": "bytes",
            "dxFileUploader-dropFile": "or Drop file here",
            "dxFileUploader-kb": "kb",
            "dxFileUploader-readyToUpload": "Ready to upload",
            "dxFileUploader-selectFile": "Select file",
            "dxFileUploader-upload": "Upload",
            "dxFileUploader-uploadFailedMessage": "Upload failed",
            "dxFileUploader-uploaded": "Uploaded",
            "dxList-nextButtonText": "More",
            "dxList-pageLoadingText": "Loading...",
            "dxList-pulledDownText": "Release to refresh...",
            "dxList-pullingDownText": "Pull down to refresh...",
            "dxList-refreshingText": "Refreshing...",
            "dxList-selectAll": "Select All",
            "dxListEditDecorator-delete": "Delete/Reject",
            "dxListEditDecorator-more": "More",
            "dxLookup-searchPlaceholder": "Minimum character number: {0}",
            "dxPager-infoText": "Page {0} of {1}",
            "dxPivotGrid-allFields": "All Fields",
            "dxPivotGrid-collapseAll": "Collapse All",
            "dxPivotGrid-columnFields": "Column Fields",
            "dxPivotGrid-dataFields": "Data Fields",
            "dxPivotGrid-expandAll": "Expand All",
            "dxPivotGrid-fieldChooserTitle": "Field Chooser",
            "dxPivotGrid-filterFields": "Filter Fields",
            "dxPivotGrid-grandTotal": "Grand Total",
            "dxPivotGrid-removeAllSorting": "Remove All Sorting",
            "dxPivotGrid-rowFields": "Row Fields",
            "dxPivotGrid-showFieldChooser": "Show Field Chooser",
            "dxPivotGrid-sortColumnBySummary": "Sort '{0}' by This Column",
            "dxPivotGrid-sortRowBySummary": "Sort '{0}' by This Row",
            "dxPivotGrid-total": "{0} Total",
            "dxRangeSlider-ariaFrom": "From {0}",
            "dxRangeSlider-ariaTill": "Till {0}",
            "dxScheduler-allDay": "All day",
            "dxScheduler-editorLabelDescription": "Description",
            "dxScheduler-editorLabelEndDate": "End Date",
            "dxScheduler-editorLabelRecurrence": "Repeat",
            "dxScheduler-editorLabelStartDate": "Start Date",
            "dxScheduler-editorLabelTitle": "Subject",
            "dxScheduler-openAppointment": "Open appointment",
            "dxScheduler-recurrenceAfter": "After",
            "dxScheduler-recurrenceDaily": "Daily",
            "dxScheduler-recurrenceEnd": "End repeat",
            "dxScheduler-recurrenceEvery": "Every",
            "dxScheduler-recurrenceMonthly": "Monthly",
            "dxScheduler-recurrenceNever": "Never",
            "dxScheduler-recurrenceOn": "On",
            "dxScheduler-recurrenceRepeatCount": "occurrence(s)",
            "dxScheduler-recurrenceRepeatDaily": "day(s)",
            "dxScheduler-recurrenceRepeatMonthly": "month(s)",
            "dxScheduler-recurrenceRepeatOnDate": "on date",
            "dxScheduler-recurrenceRepeatWeekly": "week(s)",
            "dxScheduler-recurrenceRepeatYearly": "year(s)",
            "dxScheduler-recurrenceWeekly": "Weekly",
            "dxScheduler-recurrenceYearly": "Yearly",
            "dxScheduler-switcherDay": "Day",
            "dxScheduler-switcherMonth": "Month",
            "dxScheduler-switcherWeek": "Week",
            "dxScheduler-switcherWorkWeek": "Work week",
            "dxScrollView-pulledDownText": "Release to refresh...",
            "dxScrollView-pullingDownText": "Pull down to refresh...",
            "dxScrollView-reachBottomText": "Loading...",
            "dxScrollView-refreshingText": "Refreshing...",
            "dxSwitch-offText": "OFF",
            "dxSwitch-onText": "ON",
            "validation-compare": "Values do not match",
            "validation-compare-formatted": "{0} does not match",
            "validation-custom": "Value is invalid",
            "validation-custom-formatted": "{0} is invalid",
            "validation-email": "Email is invalid",
            "validation-email-formatted": "{0} is invalid",
            "validation-mask": "Value is invalid",
            "validation-numeric": "Value must be a number",
            "validation-numeric-formatted": "{0} must be a number",
            "validation-pattern": "Value does not match pattern",
            "validation-pattern-formatted": "{0} does not match pattern",
            "validation-range": "Value is out of range",
            "validation-range-formatted": "{0} is out of range",
            "validation-required": "Required",
            "validation-required-formatted": "{0} is required",
            "validation-stringLength": "The length of the value is not correct",
            "validation-stringLength-formatted": "The length of {0} is not correct",
            //Menu
            "Home": "Home",
            "My-Task": "My Task",
            "Business-Intelligence": "Business Intelligence",
            "Business-Planning": "Business Planning",
            "Project-Management": "Project Management",
            "Quote": "Quote",
            "Finance": "Finance",
            "Basic-Data-(TBD)": "Basic Data (TBD)",
            "E-Contract-Management": "E - Contract Management",
            "System-Admin": "System Admin",
            "Market,-Competitor,-Customer": "Market, Competitor, Customer",
            "CRM": "CRM",
            "Customer-Map": "Customer Map",

            //Menu (sub) Title
            "Major-Account-Report": "Major Account Report",
            "Quotation-Tasks": "Quotation Tasks",
            "BI-Reports": "BI Reports",
            "Capability": "Capability",
            "Capacity": "Capacity",
            "NPI-Dashboard": "NPI Dashboard",
            "System-Setting": "System Setting",
            "Approval": "Approval",


            //Menu (sub) Item
            "User-Maintenance": "User Maintenance",
            "Function-Maintenance": "Function Maintenance",
            "Role-Maintenance": "Role Maintenance",
            "Plant-Maintenance": "Plant Maintenance",
            "Organization-Maintenance": "Organization Maintenance",
            "BU-Master-Maintenance": "BU Master Maintenance",
            "BU-Detail-Maintenance": "BU Detail Maintenance",
            "Organization-BOM-Maintenance": "Organization BOM Maintenance",
            "Role-Function-Setting": "Role Function Setting",
            "User-Role-Setting": "User Role Setting",
            "User-Organization-Setting": "User Organization Setting",
            "User-Plant-Setting": "User Plant Setting",
            "User-BU-Setting": "User BU Setting",
            "Competitor-Capability-Matrix": "Competitor Capability Matrix",
            "Customer-Needs-Capability-Matrix": "Customer Needs Capability Matrix",
            "Products-Tear-Down-Analysis": "Products Tear Down Analysis",
            "R&D-Reference": "R&D Reference",
            "Competitor-&-Customer": "Competitor & Customer",
            "Customer-Share-Of-Wallet": "Customer Share Of Wallet",
            "Consumer-Electronics-Reports": "Consumer Electronics Reports",
            "Capacity-Update": "Capacity Update",
            "Capacity-Report": "Capacity Report",
            "Site-Profile": "Site Profile",
            "Machine-Utilization-Report": "Machine Utilization Report",
            "Project-Initiative-Consolidate-Report": "Project Initiative Consolidate Report",
            "Quotation-Tasks": "Quotation Tasks",


            //User Define Keyword

            "login": "Login",
            "logout": "Logout",
            "logout_now": "Logout Now",
            "username": "Username",
            "password": "Password",
            "ntid": "NTID",
            "please_scan_touchid": "Please Scan Touch ID",
            "success_verify_fingerprint": "Verification Successful",
            "fail_verify_fingerprint": "Verification Failed",
            "choose_language": "Choose Language",
            "language_change_reload_page": "Changing language required to restart the app",
            "confirm_change": "Confirm Restart?",
            "language": "Language",


            //Login
            "invalid_username_password": "Invalid Username/Password",
            "menu_signin": "Sign in to start your session",

            //Company
            "company": "Company",

            "ticker": "Ticker",
            "legal_name": "Name",
            "stock_exchange": "Stock Exchange",
            "sic": "SIC",
            "long_description": "Description",
            "ceo": "CEO",
            "company_url": "URL",
            "business_address": "Address",
            "business_phone_no": "Phone",
            "cik": "CIK",
            "hq_state": "HQ State",
            "hq_country": "HQ Country",
            "inc_state": "INC State",
            "inc_country": "INC Country",
            "employees": "Employees",
            "sector": "Sector",
            "industry_category": "Category",
            "industry_group": "Group",
            "please_select_company": "Please Select Company",
            "social_media": "Social Media",
            "social_feed": "Social Feed",

            //Setting
            "setting": "Setting",
            "touchid": "Touch ID",
            "on": "On",
            "off": "Off",
            "no_internet_connection": "No Internet Connection",
            "check_vpn_connection": "Please check VPN is turn on",
            "unauthorized": "Unauthorized",
            "na": "No Information",
            "close": "Close",

            //Capacity
            "sqft": "Sqft",
            "sqft_available": "Sqft Avail",
            "floor_space": "Floor Space",
            "mfg_space": "MFG Space",
            "surplus_mfg_space": "Surplus MFG Space",
            "site": "Site",
            "site_profile": "Site Profile",
            "Taichung": "Taichung",
            "Changhua": "Changhua",
            "Suzhou": "Suzhou",
            "Yantai": "Yantai",
            "Tianjin": "Tianjin",
            "Wuxi": "Wuxi",
            "Chengdu": "Chengdu",
            "Huangpu": "HuangPu",
            "Shenzhen": "Shenzhen",
            "Penang": "Penang",
            "business": "Business",
            "key_capabilities": "Key Capabilities",

            "Tianjin Plastic": "Tianjin Plastic",
            "Tianjin Metal": "Tianjin Metal",
            "Penang Plastic": "Penang Plastic",
            "Penang FATP": "Penang FATP",
            "Shenzhen Plastic": "Shenzhen Plastic",
            "Shenzhen FATP": "Shenzhen FATP",
            "Taichung Plastic": "Taichung Plastic",
            "Taichung FATP": "Taichung FATP",
            "Taichung Metal": "Taichung Metal",
            "Chengdu Automation": "Chengdu Automation",
            "Chengdu FATP": "Chengdu FATP",
            "Chengdu Metal": "Chengdu Metal",
            "Suzhou SND": "Suzhou SND",
            "Suzhou Metal": "Suzhou Metal",
            "Suzhou SIP": "Suzhou SIP",
            "Suzhou Lounan": "Suzhou Lounan",
            "Wuxi Plastic": "Wuxi Plastic",
            "Wuxi Metal": "Wuxi Metal",
            "Wuxi FATP": "Wuxi FATP",
            "Wuxi Automation": "Wuxi Automation",
            "Yantai Plastic": "Yantai Plastic",

            //Product - Added By Eugene 2015/11/30
            "product_detail": "Product Detail",
            "product": "Product",
            "products_tear_down_analysis": "Products Tear Down Analysis",
            "apple": "Apple",
            "microsoft": "Microsoft",
            "htc": "HTC",
            "samsung": "Samsung",
            "blackberry": "BlackBerry",
            "sony": "Sony",
            "lenovo": "Lenovo",
            "nokia": "Nokia",
            "motorola": "Motorola",
            "oppo": "Oppo",
            "xiaomi": "Xiaomi",
            "smartphones": "Smartphone",
            "tablets": "Tablet",
            "phablets": "Phablet",
            "customer": "Customer",
            "type": "Type",
            "photo": "Photo",
            "operating_system": "OS",
            "display": "Display",
            "battery": "Battery",
            "camera": "Camera",
            "connectivity_and_sensors": "Connectivity & Sensors",
            "nand": "NAND",
            "sdram": "SDRAM",
            "feature": "Features",
            "cost": "Cost",
            "processor": "Processor",
            "bb+xcr": "BB + XCR",
            "remarks": "Remarks",
            "teardown_date": "Teardown Date",
            "display_touchscreen_glass": "Display, Touchscreen, Glass",
            "connectivity": "Connectivity",
            "memory_nand": "Memory NAND",
            "power_mgmt_audio": "Power Management Audio",
            "non_electronic": "Non Electronic",
            "other_mechanics_pcba": "Other Mechanics PCBA",
            "supporting_materials": "Supporting Materials",
            "manufacturing_cost": "Manufacturing Cost",
            "total": "Total",
            "selling_price": "Selling Price",
            "margin": "Margin",
            "stock": "Stock",
            "stock_current_month": "Stock (Current Month)",
            "income": "Income",
            "income_current_year": "Income (Year 2016)",
            //Company FY Report

            "totalrevenue": "Total Revenue",
            "operatingrevenue": "Operating Revenue",
            "operatingcostofrevenue": "Operating Cost Of Revenue",
            "totalcostofrevenue": "Total Cost Of Revenue",
            "totalgrossprofit": "Total Gross Profit",
            "sgaexpense": "SGA Expense",
            "rdexpense": "RD Expense",
            "totaloperatingexpenses": "Total Operating Expenses",
            "totaloperatingincome": "Total Operating Income",
            "otherincome": "Other Income / (Expense), net",
            "totalotherincome": "Total Other Income / (Expense), net",
            "totalpretaxincome": "Total Pre-Tax Income",
            "incometaxexpense": "Income Tax Expense",
            "netincomecontinuing": "Net Income / (Loss) Continuing Operations",
            "netincome": "Consolidated Net Income / (Loss)",
            "netincometocommon": "Net Income / (Loss) Attributable to Common Shareholders",
            "weightedavebasicsharesos": "Weighted Average Basic Shares Outstanding",
            "netincomecontinuing": "Net Income / (Loss) Continuing Operations",
            "basiceps": "Basic Earnings per Share",
            "weightedavedilutedsharesos": "Weighted Average Diluted Shares Outstanding",
            "dilutedeps": "Diluted Earnings per Share",
            "weightedavebasicdilutedsharesos": "Weighted Average Basic & Diluted Shares Outstanding",
            "basicdilutedeps": "Basic & Diluted Earnings per Share",
            "cashdividendspershare": "Cash Dividends to Common per Share",
            "impairmentexpense": "Impairment Charge",

            //Quote Approval
            "quote_tasks": "Quotation Tasks",
            "status": "Status",
            "review": "Open",
            "review_comments": "Review Comments",
            "approve": "Approved",
            "reject": "Rejected",
            "project": "Project",
            "customer": "Customer",
            "parts": "Parts",
            "category": "Category",
            "approve_confirmation": "Approve Confirmation",
            "reject_confirmation": "Reject Confirmation",
            "confirm_approve": "Confirm Approve",
            "confirm_reject": "Confirm Reject",
            "quote_date": "Date",
            "approval_details": "Approval Details",
            "quote_detail": "Quote Details",
            "quotation_no": "Quotation No",
            "your_quotation": "Your Quotation",
            "has_been_approved": "Has Been Approved.",
            "has_been_rejected": "Has Been Rejected.",
            "reject_reason": "Reject Reason",
            "attachment": "Attachment",
            "please_enter_reject_reason": "Please Enter Reject Reason.",
            "enter_ntid_and_password": "NTID & Password Required",

            //Capacity Report
            "capacity_report": "Capacity Report",
            "plant_type": "Plant Type",
            "site_name": "Site Name",
            "quarter": "Quarter",
        }
    })
}));

//Globalize.addCultureInfo("en", {
//    messages: {
//    //System Default

//    Back: "Back",
//    Cancel: "Cancel",
//    Clear: "Clear",
//    Done: "Done",
//    Loading: "Loading...",
//    No: "No",
//    OK: "OK",
//    Search: "Search",
//    Select: "Select...",
//    Yes: "Yes",
//    "dxCalendar-ariaWidgetName": "Calendar",
//    "dxCalendar-todayButtonText": "Today",
//    "dxCollectionWidget-noDataText": "NA",
//    "dxColorView-ariaAlpha": "Transparency",
//    "dxColorView-ariaBlue": "Blue",
//    "dxColorView-ariaGreen": "Green",
//    "dxColorView-ariaHex": "Color code",
//    "dxColorView-ariaRed": "Red",
//    "dxDataGrid-applyFilterText": "Apply filter",
//    "dxDataGrid-ariaCollapse": "Collapse",
//    "dxDataGrid-ariaColumn": "Column",
//    "dxDataGrid-ariaDataGrid": "Data grid",
//    "dxDataGrid-ariaExpand": "Expand",
//    "dxDataGrid-ariaFilterCell": "Filter cell",
//    "dxDataGrid-ariaSearchInGrid": "Search in data grid",
//    "dxDataGrid-ariaSelectAll": "Select all",
//    "dxDataGrid-ariaSelectRow": "Select row",
//    "dxDataGrid-ariaValue": "Value",
//    "dxDataGrid-columnChooserEmptyText": "Drag a column here to hide it",
//    "dxDataGrid-columnChooserTitle": "Column Chooser",
//    "dxDataGrid-columnFixingFix": "Fix",
//    "dxDataGrid-columnFixingLeftPosition": "To the left",
//    "dxDataGrid-columnFixingRightPosition": "To the right",
//    "dxDataGrid-columnFixingUnfix": "Unfix",
//    "dxDataGrid-editingAddRow": "Add a row",
//    "dxDataGrid-editingCancelAllChanges": "Discard changes",
//    "dxDataGrid-editingCancelRowChanges": "Cancel",
//    "dxDataGrid-editingConfirmDeleteMessage": "Are you sure you want to delete this record?",
//    "dxDataGrid-editingConfirmDeleteTitle": "",
//    "dxDataGrid-editingDeleteRow": "Delete",
//    "dxDataGrid-editingEditRow": "Edit",
//    "dxDataGrid-editingSaveAllChanges": "Save changes",
//    "dxDataGrid-editingSaveRowChanges": "Save",
//    "dxDataGrid-editingUndeleteRow": "Undelete",
//    "dxDataGrid-excelFormat": "Excel file",
//    "dxDataGrid-exportTo": "Export to",
//    "dxDataGrid-exportToExcel": "Export to Excel file",
//    "dxDataGrid-falseText": "false",
//    "dxDataGrid-filterRowOperationContains": "Contains",
//    "dxDataGrid-filterRowOperationEndsWith": "Ends with",
//    "dxDataGrid-filterRowOperationEquals": "Equals",
//    "dxDataGrid-filterRowOperationGreater": "Greater than",
//    "dxDataGrid-filterRowOperationGreaterOrEquals": "Greater than or equal to",
//    "dxDataGrid-filterRowOperationLess": "Less than",
//    "dxDataGrid-filterRowOperationLessOrEquals": "Less than or equal to",
//    "dxDataGrid-filterRowOperationNotContains": "Does not contain",
//    "dxDataGrid-filterRowOperationNotEquals": "Does not equal",
//    "dxDataGrid-filterRowOperationStartsWith": "Starts with",
//    "dxDataGrid-filterRowResetOperationText": "Reset",
//    "dxDataGrid-filterRowShowAllText": "(All)",
//    "dxDataGrid-groupContinuedMessage": "Continued from the previous page",
//    "dxDataGrid-groupContinuesMessage": "Continues on the next page",
//    "dxDataGrid-groupPanelEmptyText": "Drag a column header here to group by that column",
//    "dxDataGrid-headerFilterCancel": "Cancel",
//    "dxDataGrid-headerFilterEmptyValue": "(Blanks)",
//    "dxDataGrid-headerFilterOK": "OK",
//    "dxDataGrid-noDataText": "No data",
//    "dxDataGrid-searchPanelPlaceholder": "Search...",
//    "dxDataGrid-selectedRows": "Selected rows",
//    "dxDataGrid-sortingAscendingText": "Sort Ascending",
//    "dxDataGrid-sortingClearText": "Clear Sorting",
//    "dxDataGrid-sortingDescendingText": "Sort Descending",
//    "dxDataGrid-summaryAvg": "Avg: {0}",
//    "dxDataGrid-summaryAvgOtherColumn": "Avg of {1} is {0}",
//    "dxDataGrid-summaryCount": "Count: {0}",
//    "dxDataGrid-summaryMax": "Max: {0}",
//    "dxDataGrid-summaryMaxOtherColumn": "Max of {1} is {0}",
//    "dxDataGrid-summaryMin": "Min: {0}",
//    "dxDataGrid-summaryMinOtherColumn": "Min of {1} is {0}",
//    "dxDataGrid-summarySum": "Sum: {0}",
//    "dxDataGrid-summarySumOtherColumn": "Sum of {1} is {0}",
//    "dxDataGrid-trueText": "true",
//    "dxDataGrid-validationCancelChanges": "Cancel changes",
//    "dxDateBox-simulatedDataPickerTitleDate": "Select date",
//    "dxDateBox-simulatedDataPickerTitleDateTime": "Select date and time",
//    "dxDateBox-simulatedDataPickerTitleTime": "Select time",
//    "dxDateBox-validation-datetime": "Value must be a date or time",
//    "dxFileSaver-fileExported": "File exported",
//    "dxFileUploader-Gb": "Gb",
//    "dxFileUploader-Mb": "Mb",
//    "dxFileUploader-bytes": "bytes",
//    "dxFileUploader-dropFile": "or Drop file here",
//    "dxFileUploader-kb": "kb",
//    "dxFileUploader-readyToUpload": "Ready to upload",
//    "dxFileUploader-selectFile": "Select file",
//    "dxFileUploader-upload": "Upload",
//    "dxFileUploader-uploadFailedMessage": "Upload failed",
//    "dxFileUploader-uploaded": "Uploaded",
//    "dxList-nextButtonText": "More",
//    "dxList-pageLoadingText": "Loading...",
//    "dxList-pulledDownText": "Release to refresh...",
//    "dxList-pullingDownText": "Pull down to refresh...",
//    "dxList-refreshingText": "Refreshing...",
//    "dxList-selectAll": "Select All",
//    "dxListEditDecorator-delete": "Delete/Reject",
//    "dxListEditDecorator-more": "More",
//    "dxLookup-searchPlaceholder": "Minimum character number: {0}",
//    "dxPager-infoText": "Page {0} of {1}",
//    "dxPivotGrid-allFields": "All Fields",
//    "dxPivotGrid-collapseAll": "Collapse All",
//    "dxPivotGrid-columnFields": "Column Fields",
//    "dxPivotGrid-dataFields": "Data Fields",
//    "dxPivotGrid-expandAll": "Expand All",
//    "dxPivotGrid-fieldChooserTitle": "Field Chooser",
//    "dxPivotGrid-filterFields": "Filter Fields",
//    "dxPivotGrid-grandTotal": "Grand Total",
//    "dxPivotGrid-removeAllSorting": "Remove All Sorting",
//    "dxPivotGrid-rowFields": "Row Fields",
//    "dxPivotGrid-showFieldChooser": "Show Field Chooser",
//    "dxPivotGrid-sortColumnBySummary": "Sort '{0}' by This Column",
//    "dxPivotGrid-sortRowBySummary": "Sort '{0}' by This Row",
//    "dxPivotGrid-total": "{0} Total",
//    "dxRangeSlider-ariaFrom": "From {0}",
//    "dxRangeSlider-ariaTill": "Till {0}",
//    "dxScheduler-allDay": "All day",
//    "dxScheduler-editorLabelDescription": "Description",
//    "dxScheduler-editorLabelEndDate": "End Date",
//    "dxScheduler-editorLabelRecurrence": "Repeat",
//    "dxScheduler-editorLabelStartDate": "Start Date",
//    "dxScheduler-editorLabelTitle": "Subject",
//    "dxScheduler-openAppointment": "Open appointment",
//    "dxScheduler-recurrenceAfter": "After",
//    "dxScheduler-recurrenceDaily": "Daily",
//    "dxScheduler-recurrenceEnd": "End repeat",
//    "dxScheduler-recurrenceEvery": "Every",
//    "dxScheduler-recurrenceMonthly": "Monthly",
//    "dxScheduler-recurrenceNever": "Never",
//    "dxScheduler-recurrenceOn": "On",
//    "dxScheduler-recurrenceRepeatCount": "occurrence(s)",
//    "dxScheduler-recurrenceRepeatDaily": "day(s)",
//    "dxScheduler-recurrenceRepeatMonthly": "month(s)",
//    "dxScheduler-recurrenceRepeatOnDate": "on date",
//    "dxScheduler-recurrenceRepeatWeekly": "week(s)",
//    "dxScheduler-recurrenceRepeatYearly": "year(s)",
//    "dxScheduler-recurrenceWeekly": "Weekly",
//    "dxScheduler-recurrenceYearly": "Yearly",
//    "dxScheduler-switcherDay": "Day",
//    "dxScheduler-switcherMonth": "Month",
//    "dxScheduler-switcherWeek": "Week",
//    "dxScheduler-switcherWorkWeek": "Work week",
//    "dxScrollView-pulledDownText": "Release to refresh...",
//    "dxScrollView-pullingDownText": "Pull down to refresh...",
//    "dxScrollView-reachBottomText": "Loading...",
//    "dxScrollView-refreshingText": "Refreshing...",
//    "dxSwitch-offText": "OFF",
//    "dxSwitch-onText": "ON",
//    "validation-compare": "Values do not match",
//    "validation-compare-formatted": "{0} does not match",
//    "validation-custom": "Value is invalid",
//    "validation-custom-formatted": "{0} is invalid",
//    "validation-email": "Email is invalid",
//    "validation-email-formatted": "{0} is invalid",
//    "validation-mask": "Value is invalid",
//    "validation-numeric": "Value must be a number",
//    "validation-numeric-formatted": "{0} must be a number",
//    "validation-pattern": "Value does not match pattern",
//    "validation-pattern-formatted": "{0} does not match pattern",
//    "validation-range": "Value is out of range",
//    "validation-range-formatted": "{0} is out of range",
//    "validation-required": "Required",
//    "validation-required-formatted": "{0} is required",
//    "validation-stringLength": "The length of the value is not correct",
//    "validation-stringLength-formatted": "The length of {0} is not correct",

//    }
//});

//Globalize.addCultureInfo("en", {

//    messages: {

//        //Menu
//        "Home": "Home",
//        "My-Task": "My Task",
//        "Business-Intelligence": "Business Intelligence",
//        "Business-Planning": "Business Planning",
//        "Project-Management": "Project Management",
//        "Quote": "Quote",
//        "Finance": "Finance",
//        "Basic-Data-(TBD)": "Basic Data (TBD)",
//        "E-Contract-Management": "E - Contract Management",
//        "System-Admin": "System Admin",

//        //Menu (sub) Title
//        "Major-Account-Report": "Major Account Report",
//        "Quotation-Tasks": "Quotation Tasks",
//        "BI-Reports": "BI Reports",
//        "Capability": "Capability",
//        "Capacity": "Capacity",
//        "NPI-Dashboard": "NPI Dashboard",
//        "System-Setting": "System Setting",
//        "Approval": "Approval",
 

//        //Menu (sub) Item
//        "User-Maintenance": "User Maintenance",
//        "Function-Maintenance": "Function Maintenance",
//        "Role-Maintenance": "Role Maintenance",
//        "Plant-Maintenance": "Plant Maintenance",
//        "Organization-Maintenance": "Organization Maintenance",
//        "BU-Master-Maintenance": "BU Master Maintenance",
//        "BU-Detail-Maintenance": "BU Detail Maintenance",
//        "Organization-BOM-Maintenance": "Organization BOM Maintenance",
//        "Role-Function-Setting": "Role Function Setting",
//        "User-Role-Setting": "User Role Setting",
//        "User-Organization-Setting": "User Organization Setting",
//        "User-Plant-Setting": "User Plant Setting",
//        "User-BU-Setting": "User BU Setting",
//        "Competitor-Capability-Matrix": "Competitor Capability Matrix",
//        "Customer-Needs-Capability-Matrix": "Customer Needs Capability Matrix",
//        "Products-Tear-Down-Analysis": "Products Tear Down Analysis",
//        "R&D-Reference": "R&D Reference",
//        "Competitor-&-Customer": "Competitor & Customer",
//        "Customer-Share-Of-Wallet": "Customer Share Of Wallet",
//        "Consumer-Electronics-Reports": "Consumer Electronics Reports",
//        "Capacity-Update": "Capacity Update",
//        "Capacity-Report": "Capacity Report",
//        "Site-Profile": "Site Profile",
//        "Machine-Utilization-Report": "Machine Utilization Report",
//        "Project-Initiative-Consolidate-Report": "Project Initiative Consolidate Report",
//        "Quotation-Tasks": "Quotation Tasks",


//        //User Define Keyword

//        "login": "Login",
//        "logout": "Logout",
//        "logout_now": "Logout Now",
//        "username": "Username",
//        "password": "Password",
//        "ntid": "NTID",
//        "please_scan_touchid": "Please Scan Touch ID",
//        "success_verify_fingerprint": "Verification Successful",
//        "fail_verify_fingerprint": "Verification Failed",
//        "choose_language" : "Choose Language",
//        "language_change_reload_page":"Changing language required to restart the app",
//        "confirm_change": "Confirm Restart?",
//        "language": "Language",
     

//        //Login
//        "invalid_username_password": "Invalid Username/Password",
//        "menu_signin": "Sign in to start your session",

//        //Company
//        "company": "Company",

//        "ticker": "Ticker",
//        "legal_name": "Name",
//        "stock_exchange": "Stock Exchange",
//        "sic": "SIC",
//        "long_description": "Description",
//        "ceo": "CEO",
//        "company_url": "URL",
//        "business_address": "Address",
//        "business_phone_no": "Phone",
//        "cik": "CIK",
//        "hq_state": "HQ State",
//        "hq_country": "HQ Country",
//        "inc_state": "INC State",
//        "inc_country": "INC Country",
//        "employees": "Employees",
//        "sector": "Sector",
//        "industry_category": "Category",
//        "industry_group": "Group",
//        "please_select_company": "Please Select Company",
//        "social_media": "Social Media",
//        "social_feed": "Social Feed",

//        //Setting
//        "setting": "Setting",
//        "touchid": "Touch ID",
//        "on": "On",
//        "off": "Off",
//        "no_internet_connection": "No Internet Connection",
//        "check_vpn_connection": "Please check VPN is turn on",
//        "unauthorized": "Unauthorized",
//        "na": "No Information",
//        "close": "Close",

//        //Capacity
//        "sqft": "Sqft",
//        "sqft_available": "Sqft Avail",
//        "floor_space": "Floor Space",
//        "mfg_space": "MFG Space",
//        "surplus_mfg_space": "Surplus MFG Space",
//        "site": "Site",
//        "site_profile": "Site Profile",
//        "Taichung": "Taichung",
//        "Changhua": "Changhua",
//        "Suzhou": "Suzhou",
//        "Yantai": "Yantai",
//        "Tianjin": "Tianjin",
//        "Wuxi": "Wuxi",
//        "Chengdu": "Chengdu",
//        "Huangpu": "HuangPu",
//        "Shenzhen": "Shenzhen",
//        "Penang": "Penang",
//        "business": "Business",
//        "key_capabilities": "Key Capabilities",

//        "Tianjin Plastic": "Tianjin Plastic",
//        "Tianjin Metal": "Tianjin Metal",
//        "Penang Plastic": "Penang Plastic",
//        "Penang FATP": "Penang FATP",
//        "Shenzhen Plastic": "Shenzhen Plastic",
//        "Shenzhen FATP": "Shenzhen FATP",
//        "Taichung Plastic": "Taichung Plastic",
//        "Taichung FATP": "Taichung FATP",
//        "Taichung Metal": "Taichung Metal",
//        "Chengdu Automation": "Chengdu Automation",
//        "Chengdu FATP": "Chengdu FATP",
//        "Chengdu Metal": "Chengdu Metal",
//        "Suzhou SND": "Suzhou SND",
//        "Suzhou Metal": "Suzhou Metal",
//        "Suzhou SIP" : "Suzhou SIP",
//        "Suzhou Lounan": "Suzhou Lounan",
//        "Wuxi Plastic": "Wuxi Plastic",
//        "Wuxi Metal": "Wuxi Metal",
//        "Wuxi FATP": "Wuxi FATP",
//        "Wuxi Automation": "Wuxi Automation",
//        "Yantai Plastic": "Yantai Plastic",

//        //Product - Added By Eugene 2015/11/30
//        "product_detail": "Product Detail",
//        "product": "Product",
//        "products_tear_down_analysis": "Products Tear Down Analysis",
//        "apple": "Apple",
//        "microsoft": "Microsoft",
//        "htc": "HTC",
//        "samsung": "Samsung",
//        "blackberry": "BlackBerry",
//        "sony": "Sony",
//        "lenovo": "Lenovo",
//        "nokia": "Nokia",
//        "motorola": "Motorola",
//        "oppo": "Oppo",
//        "xiaomi": "Xiaomi",
//        "smartphones": "Smartphone",
//        "tablets": "Tablet",
//        "phablets": "Phablet",
//        "customer": "Customer",
//        "type": "Type",
//        "photo": "Photo",
//        "operating_system": "OS",
//        "display" : "Display",
//        "battery": "Battery",
//        "camera": "Camera",
//        "connectivity_and_sensors": "Connectivity & Sensors",
//        "nand": "NAND",
//        "sdram": "SDRAM",
//        "feature": "Features",
//        "cost":"Cost",
//        "processor": "Processor",
//        "bb+xcr" :"BB + XCR",
//        "remarks" : "Remarks",
//        "teardown_date" :"Teardown Date",
//        "display_touchscreen_glass": "Display, Touchscreen, Glass",
//        "connectivity":"Connectivity",
//        "memory_nand":"Memory NAND",
//        "power_mgmt_audio": "Power Management Audio",
//        "non_electronic": "Non Electronic",
//        "other_mechanics_pcba": "Other Mechanics PCBA",
//        "supporting_materials": "Supporting Materials",
//        "manufacturing_cost": "Manufacturing Cost",
//        "total": "Total",
//        "selling_price" : "Selling Price",
//        "margin": "Margin",
//        "stock": "Stock",
//        "stock_current_month": "Stock (Current Month)",
//        "income": "Income",
//        "income_current_year": "Income (Year 2015)",
//        //Company FY Report

//        "totalrevenue": "Total Revenue",
//        "operatingrevenue": "Operating Revenue",
//        "operatingcostofrevenue": "Operating Cost Of Revenue",
//        "totalcostofrevenue": "Total Cost Of Revenue",
//        "totalgrossprofit" : "Total Gross Profit",
//        "sgaexpense" : "SGA Expense",
//        "rdexpense" : "RD Expense",
//        "totaloperatingexpenses": "Total Operating Expenses",
//        "totaloperatingincome" : "Total Operating Income",
//        "otherincome": "Other Income / (Expense), net",
//        "totalotherincome": "Total Other Income / (Expense), net",
//        "totalpretaxincome": "Total Pre-Tax Income",
//        "incometaxexpense": "Income Tax Expense",
//        "netincomecontinuing": "Net Income / (Loss) Continuing Operations",
//        "netincome": "Consolidated Net Income / (Loss)",
//        "netincometocommon": "Net Income / (Loss) Attributable to Common Shareholders",
//        "weightedavebasicsharesos": "Weighted Average Basic Shares Outstanding",
//        "netincomecontinuing": "Net Income / (Loss) Continuing Operations",
//        "basiceps": "Basic Earnings per Share",
//        "weightedavedilutedsharesos": "Weighted Average Diluted Shares Outstanding",
//        "dilutedeps": "Diluted Earnings per Share",
//        "weightedavebasicdilutedsharesos":"Weighted Average Basic & Diluted Shares Outstanding",
//        "basicdilutedeps": "Basic & Diluted Earnings per Share",
//        "cashdividendspershare": "Cash Dividends to Common per Share",
//        "impairmentexpense": "Impairment Charge",
    
//        //Quote Approval
//        "quote_tasks": "Quotation Tasks",
//        "status": "Status",
//        "review": "Open",
//        "review_comments": "Review Comments",
//        "approve": "Approved",
//        "reject": "Rejected",
//        "project": "Project",
//        "customer": "Customer",
//        "parts": "Parts",
//        "category": "Category",
//        "approve_confirmation": "Approve Confirmation",
//        "reject_confirmation": "Reject Confirmation",
//        "confirm_approve": "Confirm Approve",
//        "confirm_reject": "Confirm Reject",
//        "quote_date": "Date",
//        "approval_details": "Approval Details",
//        "quote_detail": "Quote Details",
//        "quotation_no": "Quotation No",
//        "your_quotation": "Your Quotation",
//        "has_been_approved": "Has Been Approved.",
//        "has_been_rejected": "Has Been Rejected.",
//        "reject_reason": "Reject Reason",
//        "attachment": "Attachment",
//        "please_enter_reject_reason": "Please Enter Reject Reason.",

//        //Capacity Report
//        "capacity_report": "Capacity Report",
//        "plant_type": "Plant Type",
//        "site_name": "Site Name",
//        "quarter": "Quarter",


        
        

//    }
//});